### PR TITLE
Adds node-gyp compatibility.

### PR DESCRIPTION
**Pull request by 19h**
I published the package as `uname` because we need it for immediate deployment on our clusters. I will withdraw the  module if you fancy and this is merged.

Cheers!

### CODE REVIEW

**Comment by davepacheco** [comment]
Thanks!  Can you add me as a maintainer for the npm package?

**Comment by 19h** [comment]
Yes, sure. Moment.

**Comment by 19h** [comment]
What's your nom username? I can't find you as `davepacheco`.

**Comment by davepacheco** [comment]
I'm "dap"

**Comment by 19h** [comment]
```
npm http GET https://registry.npmjs.org/-/user/org.couchdb.user:dap
npm http 200 https://registry.npmjs.org/-/user/org.couchdb.user:dap
npm http GET https://registry.npmjs.org/uname
npm http 304 https://registry.npmjs.org/uname
npm http PUT https://registry.npmjs.org/uname/-rev/3-35104cd06a2aa46fb184250a1431b070
npm http 201 https://registry.npmjs.org/uname/-rev/3-35104cd06a2aa46fb184250a1431b070
```

You're in :) Could take some time to reflect in the web interface.

**Pull request merged**
